apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        envFrom:
        - secretRef:
            name: app-secrets
        env:
        - name: ICECAST_HOST
          value: http://icecast.midnightathletics.svc.cluster.local
        - name: LIQUIDSOAP_HOST
          value: liquidsoap.midnightathletics.svc.cluster.local
