apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: liquidsoap-secrets
  namespace: midnightathletics
spec:
  encryptedData:
    ICECAST_SOURCE_PASSWORD: AgBq/PQ96Ug1LI/x4t9xx9qHOoVLze1Jn6UYjlnT+FEIPfVUAt0Ov5btcktvAb75MC588VacgWHALi5inR76oj+8rZQ2F+nyYqvpHbLKk6ImjSaRi/dLAdLEC/rMYm5A1PDh/6Jfjy1Y+d6QXgen25PrbCHRtEiIaWAYZBHVCrrMxw1hvdcYHpbTPqDwPvb7L8oqO1qODyjb6DucNOgUdse55tAMHQlugaXfLapsG3rYa9zr1jqYN5yjER+eqZxq+JATgmtDalVLc2gWXMdTNDRhenLltQda+EyNpAljR6Zxj6OpWDrkuD08ypyf5CvaEYNr9rf8xbh7302qZgrYXNIbfFdNIryXdGMkhUWx4LnueuPADKo5kny5j1TJouawX0dFsMJN00bmG11LTBntFxR0Yb+fdsV8iuYj+2nUoP5pky9PjsYygS0H2hf4NfKpVxzGtNQurjKEl5/OcrvQ4RiFEBuBx+rs7j+WnBGuUMyTmTc11o6wz07b9TBrCpanTa6hvbvAfvDXTxanPz5KAgWCw5Y47/LZCFKsRjDVbWuOaiQxF5zLJNCc8JKMIOXdQvkF9blAHmKsfVemiEX4ya4UKYDgGYYL0J492LYIF4orpsLcdUjSKqgU/bOkbkcQDTvDwJCHUsXCytM2RUhiLDWv3OEmwfUTzRVK1uAKDTKCnOd1bU8X8+BExULFusC7KgnLvleaxzy5ZvlYBltTWnhyrKKZ7mfLvpY+WMnSuXCrtQ==
  template:
    metadata:
      creationTimestamp: null
      name: liquidsoap-secrets
      namespace: midnightathletics

