kind: Deployment
apiVersion: apps/v1
metadata:
  name: liquidsoap
spec:
  template:
    spec:
      containers:
      - name: liquidsoap
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: csi-pvc
