name: CI/CD
on: pull_request
jobs:
  build:
    name: Build and test PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Pull Request number
      run: |
        echo "BUILD_BRANCH=PR-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
    - name: Set BUILD_ID
      run: |
        echo "BUILD_ID=${BUILD_BRANCH}-$(date +%Y%m%d%H%M%S)-${GITHUB_SHA}" >> $GITHUB_ENV
    - name: Set APP_IMAGE
      run: |
        echo "APP_IMAGE=registry.digitalocean.com/coreyburmeister/midnightathletics:${BUILD_ID}" >> $GITHUB_ENV
    - name: Build
      run: |
        docker build -t ${APP_IMAGE} app
        cd kustomize/apps/app && kustomize edit set image ${APP_IMAGE}
    - name: Set up kubectl
      uses: matootie/dokube@v1.3.4
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: ${{ secrets.KUBE_CLUSTER_NAME }}
    - name: Deploy (dry run)
      run: |
        kustomize build kustomize/environments/prod | kubectl apply --server-dry-run -f -
