name: Push Master
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get branch name
      run: |
        echo "BUILD_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Set BUILD_ID
      run: |
        echo "BUILD_ID=${BUILD_BRANCH}-$(date +%Y%m%d%H%M%S)-${GITHUB_SHA}" >> $GITHUB_ENV
    - name: Set APP_IMAGE
      run: |
        echo "APP_IMAGE=coreyburmeister/midnightathletics:${BUILD_ID}" >> $GITHUB_ENV
    - name: Build
      run: |
        docker build -t registry.digitalocean.com/${APP_IMAGE} app
        cd kustomize/apps/app && kustomize edit set image registry.digitalocean.com/${APP_IMAGE}
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: |
        doctl registry login --expiry-seconds 600
    - name: Push
      run: |
        docker push registry.digitalocean.com/${APP_IMAGE}
    - name: Set up kubectl
      uses: matootie/dokube@v1.3.4
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: ${{ secrets.KUBE_CLUSTER_NAME }}
    - name: Deploy
      run: |
        kubectl apply -k kustomize/environments/prod
